FROM icr.io/cpopen/datapower/datapower-limited:10.6.2.0
COPY config /opt/ibm/datapower/drouter/config
COPY local /opt/ibm/datapower/drouter/local
COPY certs /opt/ibm/datapower/root/secure/usrcerts
USER root
RUN chown -R drouter:root /opt/ibm/datapower/drouter/config                           /opt/ibm/datapower/drouter/local                           /opt/ibm/datapower/root/secure/usrcerts
RUN set-user drouter
USER drouter
